repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: detect-private-key
- repo: local
  hooks:
  - id: mkdocs-build
    name: mkdocs-buid
    entry: bash -c 'rm -rf test; python3 -m mkdocs build --strict --quiet --site-dir test'
    language: system
