site_name: It's dangerous to go alone!
site_url: https://cosckoya.github.io
site_description: Cosckoya's Tech Toolbox
site_author: 'cosckoya'
copyright: Copyright &copy; 2026 цосцкоыа

repo_url: https://github.com/cosckoya/cosckoya.github.io
edit_uri: ""

theme:
  name: material
  variant: classic
  logo: resources/img/logo.png
  favicon: resources/img/favicon.png
  language: en
  palette:
    # MALEFICENT THEME (Purple + Acid Green)
    # Dark mode (default)
    - scheme: slate
      primary: purple
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Light mode
    - scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/circle-info
      abstract: fontawesome/solid/list-check
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/lightbulb
      success: fontawesome/solid/circle-check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/circle-xmark
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/bug
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    tag:
      default: fontawesome/solid/tag
  features:
    - navigation.sections
    - navigation.expand
    - navigation.breadcrumbs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - navigation.path
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.prune
    - content.footnote.tooltips
    - content.action.edit
    - content.action.view
    - toc.follow
    - header.autohide
    - announce.dismiss

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cosckoya
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/cosckoya
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cosckoya
    - icon: fontawesome/brands/dev
      link: https://dev.to/cosckoya
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/javier-coscolla-cabrera-95948224
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/cosckoya

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - literate-nav:
      nav_file: SUMMARY.md

extra_css:
  - resources/css/images.css
  - resources/css/snape.css

docs_dir: docs
site_dir: site
dev_addr: 127.0.0.1:8000
